version: "3.2"
services:
  apache:
    build:
      context: './docker/apache/'
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "3306:3306"
      - "9000:9000"
    volumes:
      - ./DigMenu/:/var/www/html/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ADMIN_PASS=menu
      - MYSQL_USER_NAME=menu
      - MYSQL_USER_DB=menu
      - MYSQL_USER_PASS=menu
      - PHP_IDE_CONFIG=serverName=docker-server

networks:
  frontend:
  backend:
